spring:
  ai:
    model:
      chat: ollama

    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}

      chat:
        options:
          model: ${OLLAMA_MODEL:qwen3:4b}
          temperature: ${OLLAMA_TEMPERATURE:0.2}