apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-chat-config

data:
  SERVER_PORT: "8084"

  SPRING_PROFILES_ACTIVE: "gemini"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  BOOKING_SERVICE_URL: "http://booking-service:8082"
  USER_SERVICE_URL: "http://user-service:8081"
  AUDIT_SERVICE_URL: "http://audit-service:8083"
