apiVersion: v1
kind: ConfigMap

metadata:
  name: audit-service-config

data:
  DB_URL: {{ .Values.auditService.dbUrl | quote }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.auditService.kafkaBootstrapServers | quote }}

  SERVER_PORT: {{ .Values.auditService.serverPort | quote }}

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: audit-service

spec:
  replicas: {{ .Values.auditService.replicas }}

  selector:
    matchLabels:
      app: audit-service

  template:
    metadata:
      labels:
        app: audit-service

    spec:
      containers:
        - name: audit-service
          image: {{ .Values.auditService.image }}
          imagePullPolicy: Never

          ports:
            - containerPort: {{ .Values.auditService.serverPort }}

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.auditService.serverPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.auditService.serverPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6

          envFrom:
            - configMapRef:
                name: audit-service-config

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service

metadata:
  name: audit-service

spec:
  selector:
    app: audit-service

  ports:
    - port: {{ .Values.auditService.serverPort }}
      targetPort: {{ .Values.auditService.serverPort }}

  type: ClusterIP
