apiVersion: v1
kind: ConfigMap

metadata:
  name: booking-service-config

data:
  DB_URL: {{ .Values.bookingService.dbUrl | quote }}

  USER_SERVICE_URL: {{ .Values.bookingService.userServiceUrl | quote }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.bookingService.kafkaBootstrapServers | quote }}

  SERVER_PORT: {{ .Values.bookingService.serverPort | quote }}

  JWT_EXPIRATION_MINUTES: {{ .Values.app.jwtExpirationMinutes | quote }}

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: booking-service

spec:
  replicas: {{ .Values.bookingService.replicas }}

  selector:
    matchLabels:
      app: booking-service

  template:
    metadata:
      labels:
        app: booking-service

    spec:
      containers:
        - name: booking-service
          image: {{ .Values.bookingService.image }}
          imagePullPolicy: Never

          ports:
            - containerPort: {{ .Values.bookingService.serverPort }}

          envFrom:
            - configMapRef:
                name: booking-service-config

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET

            - name: INTERNAL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: INTERNAL_SERVICE_TOKEN

---
apiVersion: v1
kind: Service

metadata:
  name: booking-service

spec:
  selector:
    app: booking-service

  ports:
    - port: {{ .Values.bookingService.serverPort }}
      targetPort: {{ .Values.bookingService.serverPort }}

  type: ClusterIP
